//============================================================================
// Name        : prac7.cpp
// Author      : dhruv kanekal
// Version     :
// Copyright   : Your copyright notice
// Description : Hello World in C++, Ansi-style
//============================================================================

/*The symbol table is generated by compiler. From this perspective, the symbol
table is a set of name-attribute pairs. In a symbol table for a compiler, the name
is an identifier, and the attributes might include an initial value and a list of lines
that use the identifier. Perform the following operations on symbol table:
a) Determine if a particular name is in the table
b) Retrieve the attributes of that name
c) Modify the attributes of that name
d) Insert a new name and its attributes
e) Delete a name and its attributes
(Use chaining with replacement and without replacement)*/

#include <iostream>
using namespace std;

class symbol
{
	string name,value;
public:
	symbol()
	{
		name="\0";
		value="\0";
	}
	friend class table;
};

class table
{
	symbol st[20][2];
public:
	void input();
	void display();
	void search();
	void modify();
	void insertnew();
	void deletenew();
};

int main()
{
	cout << "!!!Hello World!!!" << endl; // prints !!!Hello World!!!
	return 0;
}
